// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (db pull / migrate) need session-level Postgres features
    // (prepared statements, advisory locks) that the transaction-mode pooler
    // (DATABASE_URL, port 6543) does not support and silently hangs on. Use
    // the session-mode pooler (DIRECT_URL, port 5432) here — this config only
    // governs the Prisma CLI, not the app's runtime client (src/lib/prisma.ts
    // uses DATABASE_URL directly via the pg driver adapter).
    //
    // NOTE: prisma/config@7.9.1's `Datasource` type only has `url` and
    // `shadowDatabaseUrl` — no `directUrl` (that field appears in some
    // Prisma docs/skill snippets but doesn't exist on this installed
    // version; verified via node_modules/.pnpm/@prisma+config@7.9.1's own
    // .d.ts). A single `url` is sufficient since we only need one CLI-side
    // connection string here.
    url: env("DIRECT_URL"),
  },
});
